# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15, verbose_name='\u4e00\u7ea7\u6807\u7b7e\u540d')),
                ('priority', models.IntegerField(verbose_name='\u6392\u5217\u987a\u5e8f')),
                ('is_publish', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('channel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.Channel', verbose_name='\u6240\u5c5e\u9891\u9053')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'tag',
                'verbose_name': '\u4e00\u7ea7\u6807\u7b7e',
                'verbose_name_plural': '\u4e00\u7ea7\u6807\u7b7e',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15, verbose_name='\u4e8c\u7ea7\u6807\u7b7e\u540d')),
                ('priority', models.IntegerField(verbose_name='\u6392\u5217\u987a\u5e8f')),
                ('is_publish', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.Tag', verbose_name='\u4e00\u7ea7\u6807\u7b7e')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'tag_info',
                'verbose_name': '\u4e8c\u7ea7\u6807\u7b7e',
                'verbose_name_plural': '\u4e8c\u7ea7\u6807\u7b7e',
                'get_latest_by': 'created_at',
            },
        ),
    ]
