# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='channel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.Channel', verbose_name='\u6240\u5c5e\u9891\u9053'),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='tag_id',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='channel_id', chained_model_field='channel_id', on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
