# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 06:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20171107_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='tag_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='channel_id', chained_model_field='channel_id', on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
