# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 06:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20171107_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='tag_id',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='channel_id', chained_model_field='channel_id', on_delete=django.db.models.deletion.CASCADE, to='tag.Tag', verbose_name='\u6240\u5c5e\u4e00\u7ea7\u6807\u7b7e'),
        ),
    ]
