# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(max_length=20, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('cover_pic', models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=50, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\xa0\x87\xe9\xa2\x98')),
                ('video_desc', models.TextField(verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('director', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xaf\xbc\xe6\xbc\x94')),
                ('player', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98')),
                ('publish_time', models.DateField(verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('downloadable', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\x83\xbd\xe4\xb8\x8b\xe8\xbd\xbd')),
                ('is_publish', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
                ('is_serial', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('tag_id', models.ManyToManyField(to='tag.Tag', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe6\xa0\x87\xe7\xad\xbe')),
                ('tag_info', models.ManyToManyField(to='tag.TagInfo', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91id'),
        ),
    ]
