# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 07:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(choices=[(b'120', b'120*120'), (b'320', b'320*150'), (b'120', b'120*400'), (b'80', b'80*80')], max_length=10, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('cover_pic', models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('is_publish', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
                'verbose_name': '\u89c6\u9891\u5c01\u9762',
                'verbose_name_plural': '\u89c6\u9891\u5c01\u9762',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=50, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\xa0\x87\xe9\xa2\x98')),
                ('video_desc', models.TextField(verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('director', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xaf\xbc\xe6\xbc\x94')),
                ('player', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\xbc\x94\xe5\x91\x98')),
                ('publish_time', models.DateField(blank=True, null=True, verbose_name=b'\xe4\xb8\x8a\xe6\x98\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('downloadable', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\x83\xbd\xe4\xb8\x8b\xe8\xbd\xbd')),
                ('is_publish', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
                ('is_serial', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86')),
                ('cover_pic', models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channel.Channel', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\xa2\x91\xe9\x81\x93')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('tag_id', smart_selects.db_fields.ChainedManyToManyField(chained_field=b'channel_id', chained_model_field=b'channel_id', to='tag.Tag')),
                ('tag_info', smart_selects.db_fields.ChainedManyToManyField(chained_field=b'tag_id', chained_model_field=b'tag_id', to='tag.TagInfo')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video',
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='VideoCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0, verbose_name=b'\xe6\x92\xad\xe6\x94\xbe\xe6\x95\xb0')),
                ('download_count', models.IntegerField(default=0, verbose_name=b'\xe4\xb8\x8b\xe8\xbd\xbd\xe6\x95\xb0')),
                ('up_count', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('down_count', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb8\xa9\xe6\x95\xb0')),
                ('video_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_count',
                'verbose_name': '\u89c6\u9891\u7edf\u8ba1',
                'verbose_name_plural': '\u89c6\u9891\u7edf\u8ba1',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=50, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\x90\x8d')),
                ('video_index', models.IntegerField(default=0, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86\xe5\x88\x99\xe6\x8c\x89\xe9\x9b\x86\xe6\x95\xb0\xe5\xa1\xab\xe5\x86\x99', verbose_name=b'\xe5\x89\xa7\xe9\x9b\x86\xe6\x95\xb0')),
                ('video_url', models.URLField(validators=[django.core.validators.URLValidator], verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\x9c\xb0\xe5\x9d\x80')),
                ('video_icon', models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2')),
                ('desc', models.CharField(blank=True, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86\xe5\x88\x99\xe5\xbf\x85\xe9\xa1\xbb\xe5\xa1\xab\xe5\x86\x99', max_length=8, null=True, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('is_publish', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91id')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_list',
                'verbose_name': '\u89c6\u9891\u5217\u8868',
                'verbose_name_plural': '\u89c6\u9891\u5217\u8868',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91id'),
        ),
    ]
