# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image_type',
            field=models.CharField(choices=[(b'120', b'120*120'), (b'320', b'320*150'), (b'120', b'120*400'), (b'80', b'80*80')], max_length=10, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
