# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20170405_1021'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.Channel', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\xa2\x91\xe9\x81\x93'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='video',
            name='publish_time',
            field=models.DateField(blank=True, null=True, verbose_name=b'\xe4\xb8\x8a\xe6\x98\xa0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag_info',
            field=models.ManyToManyField(to='tag.TagInfo', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe8\xaf\xa6\xe6\x83\x85'),
        ),
    ]
