# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170405_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel_id',
        ),
    ]
