# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170414_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag_id',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'channel_id', chained_model_field=b'channel_id', to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='desc',
            field=models.CharField(blank=True, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86\xe5\x88\x99\xe5\xbf\x85\xe9\xa1\xbb\xe5\xa1\xab\xe5\x86\x99', max_length=8, null=True, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
    ]
