# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 06:22
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20171107_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'channel_id', chained_model_field=b'channel_id', horizontal=True, to='tag.TagInfo'),
        ),
    ]
