# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20170405_1021'),
        ('video', '0003_remove_video_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.Channel', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\xa2\x91\xe9\x81\x93'),
        ),
    ]
