# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_video_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('about_video_id', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
            ],
            options={
                'ordering': ['video_id'],
                'db_table': 'video_about',
            },
        ),
        migrations.CreateModel(
            name='VideoCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0, verbose_name=b'\xe6\x92\xad\xe6\x94\xbe\xe6\x95\xb0')),
                ('download_count', models.IntegerField(default=0, verbose_name=b'\xe4\xb8\x8b\xe8\xbd\xbd\xe6\x95\xb0')),
                ('up_count', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('down_count', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb8\xa9\xe6\x95\xb0')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_count',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=50)),
                ('video_index', models.IntegerField()),
                ('player_url', models.FileField(upload_to=tv_server.libs.UploadUtils.video_path)),
                ('icon', models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path)),
                ('desc', models.CharField(blank=True, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86\xe5\x88\x99\xe5\xbf\x85\xe9\xa1\xbb\xe5\xa1\xab\xe5\x86\x99', max_length=8, null=True)),
                ('is_publish', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_list',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891', 'verbose_name_plural': '\u89c6\u9891'},
        ),
        migrations.AddField(
            model_name='videolist',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AddField(
            model_name='videocount',
            name='video_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AddField(
            model_name='videoabout',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
