# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 07:14
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20171107_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'tag_id', chained_model_field=b'tag_id', horizontal=True, to='tag.TagInfo'),
        ),
    ]
