# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20170405_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891\u5c01\u9762'},
        ),
        migrations.AlterModelOptions(
            name='videolist',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='video',
            name='tag_id',
            field=models.ManyToManyField(to='tag.Tag', verbose_name=b'\xe4\xb8\x80\xe7\xba\xa7\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag_info',
            field=models.ManyToManyField(to='tag.TagInfo', verbose_name=b'\xe4\xba\x8c\xe7\xba\xa7\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
