# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20171205_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoabout',
            options={'verbose_name': '\u89c6\u9891\u76f8\u5173', 'verbose_name_plural': '\u89c6\u9891\u76f8\u5173'},
        ),
        migrations.AlterModelOptions(
            name='videocount',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891\u7edf\u8ba1', 'verbose_name_plural': '\u89c6\u9891\u7edf\u8ba1'},
        ),
        migrations.AlterField(
            model_name='video',
            name='tag_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'tag_id', chained_model_field=b'tag_id', to='tag.TagInfo'),
        ),
        migrations.RemoveField(
            model_name='videoabout',
            name='about_video_id',
        ),
        migrations.AddField(
            model_name='videoabout',
            name='about_video_id',
            field=models.ManyToManyField(related_name='_videoabout_about_video_id_+', to='video.VideoAbout'),
        ),
    ]
