# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20171208_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoabout',
            name='about_video_id',
        ),
        migrations.RemoveField(
            model_name='videoabout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='videoabout',
            name='video_id',
        ),
        migrations.DeleteModel(
            name='VideoAbout',
        ),
    ]
