# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0006_auto_20170406_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891\u5c01\u9762', 'verbose_name_plural': '\u89c6\u9891\u5c01\u9762'},
        ),
        migrations.AlterModelOptions(
            name='videolist',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u89c6\u9891\u5217\u8868', 'verbose_name_plural': '\u89c6\u9891\u5217\u8868'},
        ),
        migrations.AddField(
            model_name='cover',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='icon',
            field=models.ImageField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='player_url',
            field=models.FileField(upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe4\xb8\x8a\xe4\xbc\xa0'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='video_index',
            field=models.IntegerField(default=0, help_text=b'\xe5\xa6\x82\xe6\x9e\x9c\xe6\x98\xaf\xe5\x89\xa7\xe9\x9b\x86\xe5\x88\x99\xe6\x8c\x89\xe9\x9b\x86\xe6\x95\xb0\xe5\xa1\xab\xe5\x86\x99', verbose_name=b'\xe5\x89\xa7\xe9\x9b\x86\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='video_name',
            field=models.CharField(max_length=50, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\x90\x8d'),
        ),
    ]
