# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20171211_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83'),
        ),
        migrations.AddField(
            model_name='video',
            name='cover_pic',
            field=models.ImageField(default='', upload_to=tv_server.libs.UploadUtils.video_path, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87'),
            preserve_default=False,
        ),
    ]
