# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20170408_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolist',
            old_name='icon',
            new_name='video_icon',
        ),
    ]
