# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20170408_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolist',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91id'),
        ),
    ]
