# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20170412_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channel.Channel', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\xa2\x91\xe9\x81\x93'),
        ),
    ]
