# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('identity_type', models.CharField(choices=[('P', 'Phone'), ('W', 'Weibo'), ('C', 'WeChat'), ('Q', 'QQ'), ('U', 'Username')], max_length=1, verbose_name='\u767b\u5f55\u7c7b\u578b')),
                ('identifier', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('credential', models.CharField(max_length=250, verbose_name='\u5bc6\u7801')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client_auth',
                'get_latest_by': 'identity_type',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.ClientAuth')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=tv_server.libs.UploadUtils.avator_path)),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'client',
                'get_latest_by': 'created_at',
            },
        ),
    ]
