# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 07:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils
import tv_server.libs.Validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('identity_type', models.CharField(choices=[('P', 'Phone'), ('W', 'Weibo'), ('C', 'WeChat'), ('Q', 'QQ')], max_length=1, verbose_name='\u767b\u5f55\u7c7b\u578b')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('credential', models.CharField(max_length=250, verbose_name='\u5bc6\u7801')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'identity_type',
                'verbose_name': '\u5ba2\u6237\u8ba4\u8bc1',
                'verbose_name_plural': '\u5ba2\u6237\u8ba4\u8bc1',
                'db_table': 'client_auth',
            },
        ),
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_favorite',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('play_time', models.IntegerField()),
                ('is_serial', models.BooleanField()),
                ('video_list_id', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_history',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[tv_server.libs.Validators.validate_phone], verbose_name='\u624b\u673a\u53f7')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.ClientAuth', verbose_name='\u5ba2\u6237id')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6635\u79f0')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=tv_server.libs.UploadUtils.avator_path, verbose_name='\u5934\u50cf')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'client',
                'verbose_name': '\u5ba2\u6237\u8be6\u60c5',
                'verbose_name_plural': '\u5ba2\u6237\u8be6\u60c5',
                'get_latest_by': 'created_at',
            },
        ),
    ]
