# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientauth',
            name='identity_type',
            field=models.CharField(choices=[('P', 'Phone'), ('W', 'Weibo'), ('C', 'WeChat'), ('Q', 'QQ')], max_length=1, verbose_name='\u767b\u5f55\u7c7b\u578b'),
        ),
    ]
