# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_favorite',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('play_time', models.IntegerField()),
                ('is_serial', models.BooleanField()),
                ('video_list_id', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video_history',
                'get_latest_by': 'created_at',
            },
        ),
    ]
