# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_videofavorite_videohistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '\u5ba2\u6237\u8be6\u60c5', 'verbose_name_plural': '\u5ba2\u6237\u8be6\u60c5'},
        ),
        migrations.AlterModelOptions(
            name='clientauth',
            options={'get_latest_by': 'identity_type', 'verbose_name': '\u5ba2\u6237\u8ba4\u8bc1', 'verbose_name_plural': '\u5ba2\u6237\u8ba4\u8bc1'},
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.ClientAuth', verbose_name='\u5ba2\u6237id'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=tv_server.libs.UploadUtils.avator_path, verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
