# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0005_auto_20170405_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('client_id', models.IntegerField()),
                ('from_source', models.CharField(choices=[('I', 'IPhone'), ('A', 'Android'), ('P', 'PC')], max_length=1)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'comment',
                'get_latest_by': 'created_at',
            },
        ),
    ]
