# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('client_id', models.IntegerField(verbose_name='\u5ba2\u6237id')),
                ('from_source', models.CharField(choices=[('I', 'IPhone'), ('A', 'Android'), ('P', 'PC')], max_length=1, verbose_name='\u8bc4\u8bba\u6765\u6e90')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='\u89c6\u9891id')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'comment',
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
                'get_latest_by': 'created_at',
            },
        ),
    ]
