# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.BigIntegerField()),
                ('descendant_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'comment_path',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='from_source',
            field=models.CharField(choices=[('I', 'IPhone'), ('A', 'Android'), ('P', 'PC')], default='P', max_length=1, verbose_name='\u8bc4\u8bba\u6765\u6e90'),
        ),
    ]
