# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import tv_server.libs.UploadUtils


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20170406_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='cover',
            field=models.ImageField(upload_to=tv_server.libs.UploadUtils.channel_path, verbose_name='\u56fe\u6807'),
        ),
    ]
